### ISSUE TITLE
Logout Issues

### ISSUE THREAD

**Issue by bernays** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#1]
Upon logging out the user is not logged out of AzureAD only the web app. As such anybody can come along after the user presses the log out button and access the previous person's account.

I don't know where the JWT are stored in order to interact with AzureAD, but shouldn't they be deleted upon logging out so when a user logs in again they need to get new tokens?

**Comment by adelindobre** [comment]
This problem was solved and we can have an answer?

**Comment by lovemaths** [comment]
@bernays @adelindobre The session with AzureAD can be destroyed by redirecting to destroySessionUrl. The code in main branch is already updated.
 
```
In app.js

app.get('/logout', function(req, res){
  req.session.destroy(function(err) {
    req.logOut();
    res.redirect(config.destroySessionUrl);
  });
});
```
```
In config.js

exports.destroySessionUrl = 'https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=http://localhost:3000';
```
