### ISSUE TITLE
Unable to auth using the sample

### ISSUE THREAD

**Issue by hsimah** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#12]
I have downloaded the sample, but when I click the log in link I get the following message in my console:
```
{
  "name":"AzureAD: OIDC Passport Strategy",
  "hostname":"hostname",
  "pid":36232,
  "level":30,
  "msg":"authentication failed due to: In setOptions: Unable to fetch metadata",
  "time":"2017-09-21T23:32:41.284Z",
  "v":0
}
```

In my `config.js` I have set:
`identityMetadata`: `https://login.microsoftonline.com/<my guid>/.well-known/openid-configuration`. I took this GUID from a response token we receive when logging into a .NET application we also use. I have also used `https://login.microsoftonline.com/<tenantname>.onmicrosoft.com/.well-known/openid-configuration` as suggested by the `passport-azure-ad` page.
`clientID`: the `applicationId` from the registered application in the Azure Poral
`redirectUrl`: added the sample url to the registered application Reply URLs
`clientSecret`: I created a key for the registered application and copied it here
`useMongoDBSessionStore`: `false`

But this doesn't work. The error isn't particularly helpful. Can anyone point me in the direction of where I could be going wrong?

**Comment by lovemaths** [comment]
@hsimah Can you copy your identityMetadata url into your browser, and see if the url works? This library reads the information from that url. Another option is to use `https://login.microsoftonline.com/common/.well-known/openid-configuration` as the `identityMetadata` (you need to set `validateIssuer` option to false).

**Comment by hsimah** [comment]
I get back a json payload.

```
{
    "authorization_endpoint": "https://login.microsoftonline.com/<my guid>/oauth2/v2.0/authorize",
    "token_endpoint": "https://login.microsoftonline.com/<my guid>/oauth2/v2.0/token",
    "token_endpoint_auth_methods_supported": [
        "client_secret_post",
        "private_key_jwt"
    ],
    "jwks_uri": "https://login.microsoftonline.com/<my guid>/discovery/v2.0/keys",
    "response_modes_supported": [
        "query",
        "fragment",
        "form_post"
    ],
    "subject_types_supported": [
        "pairwise"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "http_logout_supported": true,
    "frontchannel_logout_supported": true,
    "end_session_endpoint": "https://login.microsoftonline.com/<my guid>/oauth2/v2.0/logout",
    "response_types_supported": [
        "code",
        "id_token",
        "code id_token",
        "id_token token"
    ],
    "scopes_supported": [
        "openid",
        "profile",
        "email",
        "offline_access"
    ],
    "issuer": "https://login.microsoftonline.com/<my guid>/v2.0",
    "claims_supported": [
        "sub",
        "iss",
        "cloud_instance_name",
        "cloud_instance_host_name",
        "cloud_graph_host_name",
        "msgraph_host",
        "aud",
        "exp",
        "iat",
        "auth_time",
        "acr",
        "nonce",
        "preferred_username",
        "name",
        "tid",
        "ver",
        "at_hash",
        "c_hash",
        "email"
    ],
    "request_uri_parameter_supported": false,
    "tenant_region_scope": "EU",
    "cloud_instance_name": "microsoftonline.com",
    "cloud_graph_host_name": "graph.windows.net",
    "msgraph_host": "graph.microsoft.com"
}
```

**Comment by danieldobalian** [comment]
Keep in mind if you use `/common` you're hitting the multi-tenant endpoint. If you're building a single tenant app, you should specify the tenant/directory ID in the field above. To make sure you were using the correct tenant/directory ID, you can go to https://portal.azure.com ->***Properties*** -> `Directory ID`

**Comment by hsimah** [comment]
@danieldobalian I'm not using common - I have my tenant url:
`https://login.microsoftonline.com/<mycompany>.onmicrosoft.com/.well-known/openid-configuration`
also tried with
`https://login.microsoftonline.com/<mycompany>.onmicrosoft.com/v2.0/.well-known/openid-configuration`

**Comment by lovemaths** [comment]
@hsimah Can you print out the error message in https://github.com/AzureAD/passport-azure-ad/blob/dev/lib/oidcstrategy.js#L789? It should tell us the reason. I should have included it in the cacheCallback error message.

```
          if (fetchMetadataError) {
              console.log(fetchMetadataError);  // <===============
              return cacheCallback(new Error(`In setOptions: Unable to fetch metadata`)); 
          }
```

**Comment by hsimah** [comment]
Ugh, too easy once I got the error. Corporate proxy strikes again. Thanks for the response- the issue is here at my end.
