### ISSUE TITLE
Office 365 Access Denied

### ISSUE THREAD

**Issue by stevo-300** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#15]
Hello,
I am trying to run the sample but have encountered the following issues:

> Error description received in the response was:  AADSTS65005: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 37faf1a0-5812-46d8-b669-105314186dd2. Resource value from request: https://graph.windows.net. Resource app ID: 00000002-0000-0000-c000-000000000000. List of valid resources from app registration: 00000003-0000-0000-c000-000000000000.
    Trace ID: 61c8cb03-50d4-47c7-bb13-23bad5480200
    Correlation ID: 50d159cc-36ff-4724-a58b-1ae49d69a1b6
    Timestamp: 2017-12-12 12:52:07Z

In my app registration I have the following delegated permissions: openid, profile, user.read, offline_access 

The user I am logging on with to test has full admin access to the tenant.

Any advice would be appreciated. 

Thanks
Steve

**Comment by jmprieur** [comment]
@stevo-300 are these delegated permissions for "Windows Azure Active Directory" (which is graph.windows.net)

**Comment by stevo-300** [comment]
That is correct as far as I can tell. (I must admit I am new to this..)

`exports.resourceURL = 'https://graph.windows.net';`

These are the permissions exactly:
https://i.imgur.com/qxUkr1L.png

the url for the app registration I am using is: https://apps.dev.microsoft.com/

**Comment by jmprieur** [comment]
I'm not familiar with passport.js, but I'd think you need to register your application in the Azure portal (https://portal.azure.com), and not in the application registration portal which is for the V2 applications. you might want to check-out the following samples: https://github.com/Azure-Samples?utf8=%E2%9C%93&q=active-directory%20node&type=&language=

**Comment by stevo-300** [comment]
@jmprieur Thank you, I registered the app like you said and this worked perfectly.

**Comment by jmprieur** [comment]
@stevo-300 : I'm glad it worked. thanks for confirming.
