### ISSUE TITLE
return/reply/redirect URL

### ISSUE THREAD

**Issue by DaveVoyles** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#18]
The Azure Portal for AAD refers to this as the ***reply url***
![image](https://user-images.githubusercontent.com/1786053/43103970-d313781c-8e9d-11e8-90f6-d6878795773a.png)

This sample refers to it as the ***redirectUrl*** in ```config.js``` & ```app.js```

And [the tutorial on Microsoft Docsl](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devquickstarts-openidconnect-nodejs) refers to it as the ***return url***.

Is there a best name / standard to use for this?

**Comment by navyasric** [comment]
Thank you for the feedback. The Reply URL on the portal refers to the redirect URL. The readme has been updated to clarify.
The sample and auth library uses the OIDC standard term of redirect url.
