### ISSUE TITLE
InvalidAuthenticationToken while using Microsoft Graph

### ISSUE THREAD

**Issue by KenySushant** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#23]
I've a Node.js API which is authenticated using passport and passport-azure-ad's OIDC strategy.

After User's authentication I get User's profile, access_token, refresh_token, sub and ISS.

Then I use the same access_token to get User's details from Microsoft graph using this API - https://graph.microsoft.com/v1.0/me

When I request, it prompts me this error:
```
{
    "error": {
        "code": "InvalidAuthenticationToken",
        "message": "Access token validation failure.",
        "innerError": {
            "request-id": "04048b3a-7636-4197-88ef-1f08d3a07c9e",
            "date": "2018-12-26T09:40:58"
        }
    }
}
```
When I use OAuth 2.0 and get the access_token and use that access_token to access the same API, the details are returned successfully.

Although even I tried matching the access_tokens returned by Open ID connect and OAuth 2.0, they differ despite logging in as a same user.

I don't understand why the access_token returned by the Open ID connect didn't worked.

**Comment by derisen** [comment]
Closing this as we are archiving this repo. Please refer to https://github.com/Azure-Samples/ms-identity-node instead
