### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by warlockdn** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#24]
I have almost tried everything but every time I am receiving the same error. Can you please help out. 

I am using the following identityMetadata 

https://login.microsoftonline.com/my_tenant_id/v2.0/.well-known/openid-configuration

The url works perfectly fine and I can see the json when I am adding the tenant id. Can u please suggest what I am doing wrong ?

`
code:"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
message:"unable to get local issuer certificate"
stack:"Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)\n    at TLSSocket.emit (events.js:189:13)\n    at TLSSocket._finishInit (_tls_wrap.js:633:8)"
`

**Comment by derisen** [comment]
Closing this as we are archiving this repo. Please refer to https://github.com/Azure-Samples/ms-identity-node instead
