### ISSUE TITLE
unsupported_response_type

### ISSUE THREAD

**Issue by mogadanez** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#26]
The flow itself works  good, I redirected to login page, login and get call back. 
but finally get error: 

```
2019-07-16T10:04:20.713148755Z {"name":"AzureAD: OIDC Passport Strategy","hostname":"0c7d7ce1193a","pid":52,"level":30,"msg":"Error received in t
he response was:  unsupported_response_type","time":"2019-07-16T10:04:20.712Z","v":0}
```

**Comment by deadbaed** [comment]
i've got the same issue, did you find a solution?

**Comment by sirtawast** [comment]
@mogadanez @x4m3 under your `App Registrations > "My App" > Authentication`, look for `Implicit Grant`. Should start logging your profile in terminal but views are still not showing for me 😕

**Comment by akkina9** [comment]
I am having the same issue...

**Comment by vramirezp** [comment]
Same

**Comment by derisen** [comment]
Closing this as we are archiving this repo. Please refer to https://github.com/Azure-Samples/ms-identity-node instead
