### ISSUE TITLE
'https://localhost:3000/microsoft') from origin 'https://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ghost** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#29]
Access to XMLHttpRequest at 'https://login.microsoftonline.com/common/oauth2/authorize?redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fauth%2Fopenid%2Freturn&response_type=code%20id_token&response_mode=form_post&client_id=qweqweqwe-qwe-qweoqw0e1-a2bb1e8d786b&state=dasdasd762375434nadm-ZtdoQJTQ1K_PiPSmy_state&nonce=adad27389213123123213&resource=https%3A%2F%2Fgraph.windows.net&scope=openid&x-client-SKU=passport-azure-ad&x-client-Ver=4.0.0' (redirected from 'https://localhost:3000/microsoft') from origin 'https://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ghost** [comment]
I'm using frontend(angularjs) for calling this API https://localhost:3000/microsoft, in the backend im redirecting (/login), etc  after some times I'm getting above error please help me on this

**Comment by derisen** [comment]
Closing this as we are archiving this repo. Please refer to https://github.com/Azure-Samples/ms-identity-node instead
