### ISSUE TITLE
Tutorial does not run

### ISSUE THREAD

**Issue by HSAR** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#5]
Following the tutorial [here](https://azure.microsoft.com/en-us/documentation/articles/active-directory-devquickstarts-openidconnect-nodejs/) results in a problem when executing `node app.js`, which stems from the validator of `passport-azure-ad` stating:

> "Invalid value for redirectUrl.The URL must be valid and be https://"

This error also exists in the completed sample project.

**Comment by lovemaths** [comment]
@HSAR The tutorial and the 'complete' branch is for passport-azure-ad versions v2.0.x. There are some changes on the options in v3.0.x, please use the code in the 'master' branch and look at sijliu/test branch to have an idea how to set the options.

**Comment by HSAR** [comment]
Thanks for the reply. One would suggest that you update your package.json, in that case, since it specifies 3.0.0 and above. For the above report I simply cloned, issued `npm install` and added appropriate code.

**Comment by HSAR** [comment]
I fixed the previous issue by adding the relevant named argument to the OIDCStrategy constructor.

However, I now have the problem that the returned token (named as the "profile" parameter in the callback) has no fields relating to "email" or "oid". It has a "sub" field, which is unique to the user, but I don't know what it means.

**Comment by lovemaths** [comment]
@HSAR Not sure why an 'oid' field is not included in the token. 'oid' and 'sub' are both unique to the user,  and 'sub' is guaranteed to be present in the token (from the endpoint you are using, i.e. v1 endpoint), so you can use 'sub' for your app (https://docs.microsoft.com/en-us/azure/active-directory/active-directory-token-and-claims). Just replace all the 'oid' with 'sub'. We no longer return an 'email' claim since v3.0.0.

**Comment by HSAR** [comment]
I figured it all out in the end. The problem was a number of missing parameters, primarily scope and validateIssuer, which I didn't think were necessary but turned out to be. I'm going to close the issue.

**Comment by AskYous** [comment]
This is very frustrating. I tried the tutorial docs.microsoft.com, and it failed. I tried to then copy the config.js from the one here, and that failed. I tried to clone the complete branch from here, and that failed. All of them give me this type of error message:

`TypeError: Invalid value for identityMetadata.The URL must be valid and be https://`

Can you at least specify in the tutorial on docs.microsoft.com that this tutorial is going to fail? I'm only giving feedback, but it was very frustrating to do through that entire tutorial, and it fails at the end. Then googling for an answer, ending up here, and seeing that tutorial, that's available for on the public web that I just wasted my time on, is out of date.

**Comment by szarouski** [comment]
@AskYous for my project I need node to authenticate via azure ADFS. I have super limited knowledge of Microsoft technologies. I cloned this repo, switched to master, replaced <tenant_guid> with value from App ID URI (in settings->properties)
 https://**this_is_a_value_you_want**.onmicrosoft.com/<random_id> so end result looks like
https:/\/login.microsoftonline.com/**this_is_a_value_you_want**.onmicrosoft.com/.well-known/openid-configuration

Also replaced clientID with Application ID & for clientSecret generated a key under settings/keys (this part is not really mentioned in the tutorial).

I also had to run mongo server on localhost (I actually used docker container as I don't want to install mongo locally) & things worked.

Good luck!

**Comment by buchizo** [comment]
I guess this sample project code does not working because that doesn't modified latest version for passport-azure-ad module. I update this sample as follows : https://gist.github.com/buchizo/9cec7d8711f10f6ecdb65afd01cc1f95
