### ISSUE TITLE
Post method issue on azure

### ISSUE THREAD

**Issue by navneetccna** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#7]
Code on local is properly working but when i uploaded the code on azure the post method is not working.

 app.post('/auth/openid/return',

Access to gate6dev.azurewebsites.net was denied

You don't have authorization to view this page.
HTTP ERROR 403

**Comment by narendrakothule** [comment]
I am facing same issue. sample code on local works fine. when it uploads on azure web app. after login it redirects to login page again. 
create user & reset password works fine. 

any comment?

**Comment by navneetccna** [comment]
Change redirect url in the config file 

redirectUrl: 'https://domain/auth/openid/return', 

Also change the user in azure portal under Azure Active Directory Settings in ALLOWED TOKEN AUDIENCES

**Comment by narendrakothule** [comment]
Thank you, 
it was node version issue. upgrade to node version to 6.x fixed.

**Comment by jjjamesjohn** [comment]
@navneetccna , how the issue was resolved, facing the same
