### ISSUE TITLE
How to use this for applicationinsights

### ISSUE THREAD

**Issue by navneetccna** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#8]
I want to get json data as explain in rest api doc https://dev.applicationinsights.io/documentation/overview

customEvents 
 	 | where customDimensions.teamId == '8bcb0466-8227-4de4-b001-b70381b9cd04' 

As the rest api have limit of 15 call per min and 1500 per day  as doc https://dev.applicationinsights.io/documentation/Authorization/Rate-limits says to use Azure API and Azure Active Directory but there is no example available for that. This is possible in this SDK

**Comment by navyasric** [comment]
@navneetccna This sample demonstrates how to authenticate users to a node.js app using Azure AD. The passport-azure-ad SDK used is an authentication library. It does not provide application insights integration.
